### ISSUE TITLE
v0.2.6 Docker 27.3.1 | Error: Unable to fetch zone ID for domain xyz.de

### ISSUE THREAD

**Issue by Crash1602** [filiparag/hetzner_ddns#20]
Hello,

I have an issue with version 0.2.6 where I receive the following error message:

```
[2024-12-12 11:57:29] Started Hetzner DDNS daemon
[2024-12-12 11:57:29] Reading configuration from /etc/hetzner_ddns.conf
[2024-12-12 11:57:29] Error: Unable to fetch zone ID for domain xyz.de
[2024-12-12 11:58:00] Retrying to fetch zone and record data
[2024-12-12 11:58:00] Error: Unable to fetch zone ID for domain xyz.de
[2024-12-12 11:58:31] Retrying to fetch zone and record data
[2024-12-12 11:58:31] Error: Unable to fetch zone ID for domain xyz.de
[2024-12-12 11:59:02] Retrying to fetch zone and record data
[2024-12-12 11:59:02] Error: Unable to fetch zone ID for domain xyz.de
[2024-12-12 11:59:33] Retrying to fetch zone and record data
```

This is what my hetzner_ddns.conf looks like:

```
# Seconds between updates / TTL value
interval='60'

# Hetzner DNS API key
key='arevaregFTHFbarfgdtshtDZRTbfgs'

# Top level domain name
domain='xyz.de'

# Space separated host subdomains (@ for domain itself)
records='test test2 test3'

# Enable updating A records (IPv4)
ipv4=true

# Enable updating AAAA records (IPv6)
ipv6=true
```

The relevant part of my stack:

```
# xyz.de DDNS  
  xyz:
    image: filiparag/hetzner_ddns:0.2.6
    container_name: 'hetznerddns-xyz'
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/hetznerddns-xyz-prod/_data/hetzner_ddns.conf:/etc/hetzner_ddns.conf:ro #ReadOnly
    network_mode: host
```

With version 0.2.5, I don't have a problem with any of my four containers. As soon as I update the config file and include 0.2.6, I get the error on all four of them.

What could be causing this?

Thanks!

**Comment by filiparag** [comment]
Your configuration files seem okay. New version `0.2.6` doesn't modify any of zone ID fetching code, so I'm not sure why it breaks after upgrading from `0.2.5`.

I would suggest you pin the version to `0.2.5` for now, and let's see if anyone else encounters the same issue.

**Comment by Crash1602** [comment]
I have just tested a container on another Docker host (same Version and System-Config) with version DDNS ```0.2.6``` using the current configuration including IPv4 and IPv6 parameters. There is no 'fetch' error there.

Unfortunately, this does not give me a new idea where the cause might lie.

**Comment by filiparag** [comment]
> Gives a debug log that I can enable?

There is no option for additional debugging information, as this is a fairly simple utility. However, you might try manually running [`curl` commands this script uses](https://github.com/filiparag/hetzner_ddns/blob/0.2.6/hetzner_ddns.sh#L159-L160) inside and outside the container to see what causes the issue.

**Comment by Crash1602** [comment]
Thank you very much for your help. I executed the command  ```/ # curl "https://dns.hetzner.com/api/v1/zones" -H "Auth-API-Token: WjcswEAFaASdsdasdasd"``` on the host and in the Docker container.

1) On the Docker host, all information could be retrieved (2450 characters).
2) In a Docker container with version ```0.2.5```, all information could be retrieved (2450 characters).
3) In a Docker container with version ```0.2.6```, I receive the error curl: (6) Could not resolve host: dns.hetzner.com

**Comment by Crash1602** [comment]
When I specify the DNS parameters as follows, fetching the ZoneIDs works during the runtime of the script with version ```0.2.6```.

The script seems not to be querying the correct DNS servers during runtime.

```
# xyz.de DDNS  
  xyz:
    image: filiparag/hetzner_ddns:0.2.6
    container_name: 'hetznerddns-xyz'
    dns:
     - 8.8.8.8
     - 1.1.1.1
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/hetznerddns-xyz-prod/_data/hetzner_ddns.conf:/etc/hetzner_ddns.conf:ro #ReadOnly
    network_mode: host
```
