### ISSUE TITLE
arm64 build for the docker version?

### ISSUE THREAD

**Issue by lazz0** [filiparag/hetzner_ddns#24]
Hello everyone,

I wanted to run hetzner_ddns on a raspberry pi but the provided version on DockerHub does not work for the arm64-architecture.

I was able to build it myself locally on the raspberry pi from your Dockerfile with `sudo docker build --platform linux/arm64 -t hetzner_ddns .` in the directory of the Dockerfile and then run it with this slightly modified `docker-compose.yaml`file:
```
services:
  hetzner-ddns:
    image: hetzner_ddns
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - ./hetzner_ddns.conf:/etc/hetzner_ddns.conf:ro
```

Could you also provide an arm64-version via DockerHub? It would make life easier for us sparetimetinkerers with our raspberry pis :)

Kind regards,
lazz0

**Comment by filiparag** [comment]
Hi,

The container image on Docker Hub is namespaced under my username, so you have to use `filiparag/hetzner_ddns` for the image name.

Secondly, released images are not multiplatform, so you have to specify the architecture in the tag name, which would be `latest-arm64` or `0.2.6-arm64`.

Try this configuration and report back:

```yml
services:
  hetzner-ddns:
    image: filiparag/hetzner_ddns:latest-arm64
    restart: unless-stopped
    volumes:
      - ./hetzner_ddns.conf:/etc/hetzner_ddns.conf:ro
```
